### PR TITLE
Feat Add Github List

### PR DESCRIPTION
**Pull request by dawksh**
Maybe make a new branch for it.

### CODE REVIEW

**Comment by friendly-developer** [comment]
Let's create issues mentioning the changes that we would want to include. That way every PR is accountable.

**Comment by dawksh** [comment]
@sadanandpai can you check what did I do wrong? there is some import issue and I don't understand it.

**Comment by friendly-developer** [comment]
> @sadanandpai can you check what did I do wrong? there is some import issue and I don't understand it.

it is because a SCSS loader is not present in the webpack configuration I think

**Comment by dawksh** [comment]
@friendly-developer it was a silly mistake from my side, a simple capitalization mistake. @sadanandpai if this looks okay then consider merging this.

**Pull request merged**
